# -*- coding: utf-8 -*-
"""Freelancers final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdaaG4k_mHETJ17wNsfBqR5wTmWpxl2D

**Global Freelancers Market Analysis: An Exploratory Data Analysis Using Python**

**Asna Fathima**

**DAF30**

**Aim**

The aim of this project is to analyze the Global Freelancers dataset using data preprocessing, exploratory data analysis, and visualization techniques to identify patterns and trends in freelancer earnings.

**Introduction**

With the growth of the internet and digital platforms, the way people work has changed significantly. Many professionals now work as freelancers, providing their services online to clients from different parts of the world. Freelancers operate in various fields such as technology, design, writing, and marketing. Online freelance platforms have made it easier for clients and freelancers to connect, creating a global marketplace for digital services.

Studying freelancer data helps in understanding how the freelance industry operates. By analyzing factors such as earnings, experience, and job categories, we can identify important trends and patterns in the freelance market. Data analytics plays a crucial role in uncovering these insights and understanding how different factors influence a freelancer’s success and income.

This project focuses on analyzing the Global Freelancers dataset using Python tools such as Pandas, NumPy, Matplotlib, and Seaborn. The analysis involves data cleaning, preprocessing, and visualization to uncover meaningful patterns and relationships within the dataset.

**Problem Statement**

The dataset contains raw and unstructured data with possible missing values, inconsistencies, and variations in format. Without proper analysis, it is difficult to understand how different factors such as experience, job category, and demographics affect freelancer earnings.

The problem is to clean and analyze the dataset to identify relationships, trends, and key factors that influence freelancer income and distribution.

**Dataset Source**

The dataset used in this project is the **Global Freelancers Dataset**, obtained from Kaggle.

**Source Link:**

https://www.kaggle.com/api/v1/datasets/download/urvishahir/global-freelancers-raw-dataset

**Dataset Description**

The dataset contains information about freelancers, including:

- Age  
- Gender  
- Country
- Job Category
- Primary Skill  
- Years of Experience  
- Hourly Rate (USD)  

These features help in analyzing freelancer demographics and income patterns.

**Objectives**

- To understand the structure and content of the dataset

- To clean and preprocess the data

- To handle missing values and remove duplicates

- To analyze freelancer demographics and job categories

- To study the relationship between experience and earnings

- To perform exploratory data analysis (EDA)

- To create meaningful visualizations

**Tools Used**
*   Python
*   Google Colab
*   Pandas
*   NumPy
*   Matplotlib
*   Seaborn

**Data Loading and Initial Overview**

In this section, the dataset is imported and an initial overview is performed to understand its structure, including the number of rows and columns, data types, and summary statistics.

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""In this step, essential Python libraries are imported:

- Pandas (pd): Used for data manipulation and analysis  
- NumPy (np): Used for numerical computations  
- Matplotlib (plt): Used for creating basic visualizations  
- Seaborn (sns): Used for advanced statistical visualizations  

These libraries will be used throughout the project for data analysis and visualization.

**Upload the dataset**
"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("global_freelancers_raw.csv")

"""The dataset was loaded into a Pandas DataFrame using the read_excel() function for further processing and analysis.

**Preview of Dataset**
"""

df.head()

"""*   This function displays the first few rows of the dataset.
*   This helps in understanding the structure of the data and the type of information present in each column.

**Number of Rows and Columns**
"""

df.shape

"""*   This step helps us to understand the size of the dataset by identifying the total number of rows and columns.


*  This dataset contains 1000 rows and 12 columns.

**Data Types of Each Column**
"""

df.info()

"""This function provides information about the dataset, including column names, data types, and non-null values.

From the output, it can be observed that:
- The dataset contains 12 columns  
- Some columns have missing values such as age, years_of_experience, hourly_rate (USD), rating, is_active, and client_satisfaction  
- Data types include float64 and object (categorical/text data)

This step helps in identifying columns that require data cleaning and type conversion.

**Statistical Summary**
"""

df.describe().round(2)

"""This function provides statistical summary of numerical columns.

It includes measures such as mean, standard deviation, minimum, and maximum values.

*   The average value of age is 40.51
*   The minimum and maximum values of years_of_experience are 0 and 41
*   There is variation in the data, indicating that the values are spread out and not all the same (data variability)

This helps in understanding the distribution and spread of the dataset.

**Data Pre-processing**

Data preprocessing is an essential step in data analysis. It involves cleaning and transforming raw data into a structured format suitable for analysis.

In this stage, missing values are handled, duplicate records are removed, data types are corrected, and new features are created to improve the quality of the dataset.

**Handling Missing Values**
"""

df.isnull().sum()

"""*   This function is used to identify missing values in each column of the dataset.


*   From the output, it was observed that several columns contain missing values such as age, years_of_experience, hourly_rate (USD), rating, is_active, and client_satisfaction.

**Filling numerical columns**
"""

df["age"].fillna(df["age"].median(), inplace=True)

df["years_of_experience"].fillna(df["years_of_experience"].median(), inplace=True)

df["rating"].fillna(df["rating"].median(), inplace=True)

"""*   Missing values in numerical columns such as **age, years_of_experience, and rating** were replaced using the median value.

*   The median is preferred over the mean because it is less affected by extreme values (outliers), making it a reliable measure for data imputation.

**Cleaning and Standardizing Columns**

Cleaning and standardizing columns ensures that the dataset is consistent, accurate, and ready for analysis by removing errors, handling missing values, and making the data easier to interpret.

**Hourly Rate (USD)**
"""

df["hourly_rate (USD)"] = df["hourly_rate (USD)"].astype(str)
df["hourly_rate (USD)"] = df["hourly_rate (USD)"].str.replace("USD","")
df["hourly_rate (USD)"] = df["hourly_rate (USD)"].str.replace("$","")
df["hourly_rate (USD)"] = pd.to_numeric(df["hourly_rate (USD)"], errors="coerce")
df["hourly_rate (USD)"].fillna(df["hourly_rate (USD)"].median(), inplace=True)

"""


*   The hourly_rate (USD) column contained mixed values such as "USD 100", "$40", and numeric values.

*   Non-numeric characters were removed, and the column was converted into numeric format. Missing values were filled using the median due to possible outliers.

"""

df["hourly_rate (USD)"].head()

"""**Client Satisfaction**"""

df["client_satisfaction"] = df["client_satisfaction"].astype(str)
df["client_satisfaction"] = df["client_satisfaction"].str.replace("%","")
df["client_satisfaction"] = pd.to_numeric(df["client_satisfaction"], errors="coerce")
df["client_satisfaction"].fillna(df["client_satisfaction"].median(), inplace=True)

"""The client_satisfaction column contained percentage values. The percentage symbol and extra spaces were removed, and the column was converted into numeric format. Missing values were replaced using the median."""

df["client_satisfaction"].head()

"""**Gender**"""

df["gender"] = df["gender"].astype(str).str.strip().str.lower()

df["gender"] = df["gender"].replace({
    "m": "male",
    "f": "female"
})

df["gender"] = df["gender"].str.title()

"""The gender column was standardized by removing spaces and converting values into consistent categories such as Male and Female."""

df["gender"].unique()

"""**Is Active**"""

df["is_active"] = df["is_active"].astype(str)

df["is_active"] = df["is_active"].replace({
    "1": "Yes",
    "Y": "Yes",
    "yes": "Yes",
    "True": "Yes",

    "0": "No",
    "N": "No",
    "no": "No",
    "False": "No"
})

df["is_active"] = df["is_active"].replace("nan", np.nan)

df["is_active"].fillna(df["is_active"].mode()[0], inplace=True)

df["is_active"].unique()

"""The is_active column contained inconsistent values such as "1", "Y", "True", "0", "N", and "False", along with missing values.

First, the column was converted into string format to handle mixed data types. Then, all values were standardized into two consistent categories:
- "Yes" for active freelancers  
- "No" for inactive freelancers  

During conversion, missing values were represented as the string "nan". These were converted back into proper missing values using replace().

Finally, missing values were filled using the mode (most frequent value) to maintain data consistency and avoid introducing new categories.

This ensures that the column is clean, consistent, and suitable for analysis.

**Country**
"""

df["country"].unique()

"""Primary Skill"""

df["primary_skill"].unique()

df.head()

df.isnull().sum()

"""**Removing Duplicates**"""

df.duplicated().sum()

"""*   Duplicate rows can affect the accuracy of analysis. Therefore, the dataset is checked for duplicate records.
*   After checking there is no duplicate found.

**Creating Derived Columns**

**Creating Experience Level Category**
"""

df["experience_level"] = pd.cut(
    df["years_of_experience"],
    bins=[-1, 2, 5, 10, 50],
    labels=["Beginner", "Intermediate", "Advanced", "Expert"]
)

"""A new column named experience_level was created to categorize freelancers based on their years of experience.

The pd.cut() function was used to divide the continuous numerical data into meaningful categories:
- Beginner (0–2 years)
- Intermediate (3–5 years)
- Advanced (6–10 years)
- Expert (10+ years)

This transformation simplifies analysis by grouping freelancers into levels, making it easier to compare performance and trends across experience categories.

**Identifying High-Value Freelancers**
"""

df["high_value_freelancer"] = df["hourly_rate (USD)"] > 50

df["high_value_freelancer"] = df["high_value_freelancer"].map({
    True: "Yes",
    False: "No"
})

"""A new column named high_value_freelancer was created to identify freelancers earning more than 50 USD per hour.

In this,
- Yes → High-value freelancer
- No → Others

This helps in segmenting freelancers based on earning potential and allows focused analysis on high-income individuals.
"""

df.head()

"""**Filtering**

**Filtering High-Earning Freelancers**
"""

high_earning = df[df["hourly_rate (USD)"] > 50]
high_earning.head()

"""Filtering was applied to extract freelancers who earn more than 50 USD per hour.

This subset of data helps in performing focused analysis on high-earning freelancers, allowing better understanding of their characteristics and patterns.

**Exploratory Data Analysis (EDA)**

Exploratory Data Analysis (EDA) is the process of examining and understanding a dataset before analysis. It involves summarizing, visualizing, and detecting patterns in the data. EDA helps make better decisions for modeling and drawing insights.

**Statistical Summary of Numerical Data**
"""

df.describe().round(2)

"""**Univariate analysis**

Univariate analysis studies one variable at a time to understand its distribution and characteristics.

**Country Distribution**
"""

df["country"].value_counts()

"""This is categorical univariate data showing the number of entries per country.
**South Korea (68)** has the highest count, while **Brazil (31)** has the lowest.
It shows which countries have more or fewer freelancers in the dataset.

**Primary Skill Distribution**
"""

df["primary_skill"].value_counts()

"""- DevOps is the most common skill with 112 freelancers, indicating strong demand and popularity in this domain.

- UI/UX Design (109) and Blockchain Development (105) also show high representation, suggesting growing importance of design and emerging technologies.

- Skills like Web Development and Mobile Apps have nearly similar counts, showing consistent demand in development-related roles.

- AI (100) and Data Analysis (96) reflect increasing interest in data-driven and intelligent systems.

- Graphic Design and Machine Learning have equal counts (93), indicating moderate presence in the dataset.

- Cybersecurity has the lowest count (86), but still remains a significant and relevant skill.

**Gender Distribution**
"""

df["gender"].value_counts()

"""- The number of male and female freelancers is almost equal.

- Males have a slightly higher count than females.

**Active Status Distribution**
"""

df["is_active"].value_counts()

"""-  There are more inactive freelancers than active ones.
-  The difference is noticeable, showing lower active participation.

**Experience Level Distribution**
"""

df["experience_level"].value_counts()

"""- Experts have the highest count, showing strong representation of highly experienced freelancers.
- Advanced and Beginner levels also have a good number of freelancers.
- Intermediate has the lowest count, indicating fewer mid-level freelancers.

**Bivariate analysis**  

Bivariate analysis studies the relationship between two variables to see how one affects or relates to the other.

**Experience Level vs Earnings**
"""

df.groupby("experience_level")["hourly_rate (USD)"].agg(['mean','count']).round(2)

"""- Experts have the highest average hourly rate (53.26 USD).
- Beginners also have a relatively high rate (51.38 USD).
- Intermediate level has the lowest average rate (47.41 USD).

The differences are not very large, but experience still shows some impact.

**Country vs Rating**
"""

df.groupby("country")["rating"].agg(['mean','count']).round(2)

"""The average ratings are fairly similar across countries, with only slight differences. This indicates that freelancer performance is consistent globally, with a few countries showing slightly higher ratings.

**Skill vs Earnings**
"""

df.groupby("primary_skill")["hourly_rate (USD)"].agg(['mean','count']).round(2)

"""Hourly rates are fairly similar across all skills, but technical skills like Cybersecurity, Web Development, and DevOps tend to earn slightly higher.

**Active Status vs Earnings**
"""

df.groupby("is_active")["hourly_rate (USD)"].agg(['mean','count']).round(2)

"""Active freelancers tend to earn slightly more than inactive freelancers, suggesting that being active may be linked to better earning opportunities.

**Multivariate Analysis**

Multivariate analysis examines more than two variables together to understand complex relationships.

**Country & Experience vs Rating**
"""

df.groupby(["country", "experience_level"])["rating"].agg(['mean','count']).round(2)

"""- Ratings vary across both countries and experience levels.

- In many countries, experienced freelancers (Advanced/Expert) tend to have higher ratings than beginners.

- However, this pattern is not consistent everywhere, as some beginners also have high ratings.

- For example, in the United States, beginners have a high rating (3.86), while experts have a slightly lower rating (2.52).

**Pivot Table Analysis**

**Earnings by Experience and Gender**
"""

pd.pivot_table(
    df,
    values="hourly_rate (USD)",
    index="experience_level",
    columns="gender",
    aggfunc=["mean","count"]
).round(2)

"""The analysis shows that hourly rates are nearly equal between male and female freelancers across all experience levels. The number of freelancers increases with experience, with the highest count at the expert level. Overall, experience has a slight impact on earnings, but gender does not significantly affect pay.

**Correlation Analysis**
"""

df.corr(numeric_only=True).round(2)

"""- Age & Experience (0.60) → This shows a moderate positive correlation, meaning as age increases, experience also increases (which is expected).

- Experience & Hourly Rate (0.08) → Very weak positive correlation, so experience slightly increases earnings, but not strongly.

- Hourly Rate & Rating (0.02) → Almost no relationship, meaning higher pay doesn’t guarantee better ratings.

- Client Satisfaction & all variables (~0) → No strong correlation, so satisfaction is not directly dependent on age, experience, or earnings.

The only meaningful relationship is between age and experience, while all other factors show weak or negligible correlation, suggesting that freelancer success depends on multiple factors, not just one.

**Data visualization**

It is the process of representing data using charts, graphs, or plots to make it easier to understand.
It helps to identify patterns, trends, and outliers quickly.
Common visualizations include bar charts, histograms, scatter plots, pie charts, line charts, and heatmaps.

**Color of the graphical representation**
"""

violet_palette = [
    "#F3E5F5", "#E1BEE7", "#CE93D8", "#BA68C8", "#AB47BC",
    "#9C27B0", "#8E24AA", "#7B1FA2", "#6A0DAD", "#4A148C"
]

"""A consistent violet color palette is defined to maintain uniform and professional visualization styling.

**1. Number of Freelancers by Country**
"""

plt.figure(figsize=(10,5))
sns.countplot(x="country", data=df, palette=violet_palette)
plt.xticks(rotation=45)
plt.title("Number of Freelancers by Country")
plt.xlabel("Country")
plt.ylabel("Count")
plt.show()

"""Freelancer distribution varies across countries, with **South Korea** having the highest participation, while countries like Br**azil and Japan** have comparatively fewer freelancers.

**2. Gender Distribution**
"""

gender_counts = df["gender"].value_counts()
plt.figure(figsize=(6,6))
plt.pie(gender_counts, labels=gender_counts.index, autopct="%1.1f%%", colors=["#CE93D8", "#BA68C8"])
plt.title("Gender Distribution of Freelancers")
plt.show()

"""The gender distribution among freelancers is almost balanced, with males representing 51% and females 49%, indicating no significant gender gap in participation.

**3.Hourly Rate Distribution**
"""

plt.figure(figsize=(8,5))
sns.histplot(df["hourly_rate (USD)"], bins=15, kde=True, color="#CE93D8")
plt.title("Distribution of Hourly Rate (USD)")
plt.xlabel("Hourly Rate (USD)")
plt.ylabel("Frequency")
plt.show()

"""This chart shows the distribution of hourly rates among freelancers. It can be observed that most freelancers charge within a moderate price range, with fewer freelancers at very high rates. The distribution indicates that while there are some high-earning individuals, the majority of freelancers fall within common market pricing levels. This suggests a competitive pricing structure where only a smaller proportion of freelancers command premium rates.

**4. Hourly Rate by Experience Level**
"""

plt.figure(figsize=(8,5))
sns.boxplot(x="experience_level", y="hourly_rate (USD)", data=df, palette=violet_palette)
plt.title("Hourly Rate by Experience Level")
plt.xlabel("Experience Level")
plt.ylabel("Hourly Rate (USD)")
plt.show()

"""This chart shows the distribution of hourly rates across different experience levels of freelancers. It can be observed that as experience level increases from beginner to expert, the overall range and upper limits of hourly rates also increase. Expert and advanced freelancers tend to have higher maximum rates compared to beginners. However, there is some overlap between the groups, indicating that certain less experienced freelancers may still charge competitive rates. This suggests that while experience influences pricing, other factors such as skill specialization and demand also play a role.

**5. Years of Experience vs Hourly Rate**
"""

plt.figure(figsize=(8,5))
sns.scatterplot(x="years_of_experience", y="hourly_rate (USD)", data=df, color="mediumvioletred", s=60)
plt.title("Years of Experience vs Hourly Rate")
plt.xlabel("Years of Experience")
plt.ylabel("Hourly Rate (USD)")
plt.show()

"""This scatter plot shows the relationship between years of experience and hourly rate. The data points are widely spread across the graph, indicating high variability in earnings. There is no strong upward trend, suggesting a weak relationship between experience and pay. Overall, having more experience does not always guarantee higher hourly rates.

**6. Average Rating by Experience Level**
"""

avg_rating = df.groupby("experience_level")["rating"].mean().reset_index()
plt.figure(figsize=(8,5))
sns.lineplot(x="experience_level", y="rating", data=avg_rating, marker="o", color="darkviolet")
plt.title("Average Rating by Experience Level")
plt.xlabel("Experience Level")
plt.ylabel("Average Rating")
plt.show()

"""This chart shows the average ratings of freelancers across different experience levels. It can be observed that ratings slightly increase as experience level rises from beginner to expert. While the difference is not very large, expert freelancers tend to have the highest average ratings. This indicates that more experienced freelancers generally provide better quality service, leading to improved client satisfaction.

**7. Average Hourly Rate by Primary Skill**
"""

avg_skill_rate = df.groupby("primary_skill")["hourly_rate (USD)"].mean().reset_index()
plt.figure(figsize=(10,5))
sns.barplot(x="primary_skill", y="hourly_rate (USD)", data=avg_skill_rate, palette=violet_palette)
plt.xticks(rotation=45)
plt.title("Average Hourly Rate by Primary Skill")
plt.xlabel("Primary Skill")
plt.ylabel("Average Hourly Rate (USD)")
plt.show()

"""This chart shows the average hourly rates of freelancers across different primary skills. It can be observed that certain technical skills such as Web Development, Cybersecurity, and DevOps tend to have slightly higher average hourly rates compared to other fields. While the variation is not extremely large, it indicates that specialized and in-demand skills generally command better pricing. This suggests that skill type plays an important role in determining earning potential in freelancing.

**8. Age Distribution of Freelancers**
"""

plt.figure(figsize=(8,5))
sns.histplot(df["age"], bins=15, kde=True, color="#7B1FA2")
plt.title("Age Distribution of Freelancers")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

"""This chart shows the distribution of freelancers based on age. It can be observed that freelancers are spread across a wide age range, with a higher concentration in the mid-age groups. This indicates that freelancing is more popular among individuals with some level of professional experience rather than very young or very old age groups. The smooth curve further suggests a relatively balanced distribution without extreme peaks.

**9. Top 10 Countries**
"""

top_countries = df['country'].value_counts().head(10)
plt.figure(figsize=(10,5))
sns.barplot(x=top_countries.values, y=top_countries.index, palette=violet_palette)
plt.title("Top 10 Countries by Freelancer Count")
plt.xlabel("Number of Freelancers")
plt.ylabel("Country")
plt.show()

"""This chart shows that a few countries dominate freelancing, indicating regional concentration of opportunities.
**South Korea** has the highest number of freelancers among the top 10 countries, followed by **Canada and Germany**, while **Russia** has the lowest count in this group.

**10. Skill Distribution**
"""

plt.figure(figsize=(6,6))
df["primary_skill"].value_counts().head(5).plot(
    kind="pie",
    autopct="%1.1f%%",
    colors=["#F3E5F5", "#E1BEE7", "#CE93D8", "#BA68C8", "#AB47BC"]
)

plt.title("Skill Distribution")
plt.ylabel("")
plt.show()

"""This chart shows the proportion of freelancers across different skill categories. It can be observed that DevOps has the highest share at 21.1%, followed closely by UI/UX Design at 20.5%. Blockchain Development (19.7%), Web Development (19.5%), and Mobile Apps (19.2%) also contribute nearly equally. The distribution is quite balanced across all skill categories, indicating that demand is spread across multiple domains rather than being concentrated in a single skill area.

**11. Active vs Rating**
"""

plt.figure(figsize=(6,5))
sns.barplot(x="is_active", y="rating", data=df, palette=violet_palette)

plt.title("Active vs Rating")
plt.xlabel("Active Status")
plt.ylabel("Average Rating")
plt.show()

"""Freelancers who are currently active tend to have slightly higher average ratings compared to inactive freelancers, indicating better engagement or recent performance.

**12. Client Satisfaction**
"""

plt.figure(figsize=(8,5))
sns.histplot(df["client_satisfaction"], bins=20,
             color="#BA68C8")

plt.title("Client Satisfaction Distribution")
plt.xlabel("Client Satisfaction")
plt.ylabel("Frequency")
plt.show()

"""This histogram shows the distribution of client satisfaction scores among freelancers. Most values are concentrated around 75–85, indicating generally high satisfaction levels. Overall, the data suggests that clients are mostly satisfied with freelancer services.

**13. Correlation of Numeric Variables**
"""

plt.figure(figsize=(8,6))
corr = df[["age","years_of_experience","hourly_rate (USD)","rating"]].corr()
sns.heatmap(corr, annot=True, cmap="Purples", linewidths=0.5)
plt.title("Correlation Heatmap of Numeric Variables")
plt.show()

"""This **heatmap** shows the correlation between numerical variables such as age, years of experience, hourly rate, and rating. It can be observed that age and years of experience have a moderate positive correlation (around 0.6), indicating that as age increases, experience also tends to increase. However, hourly rate and rating show very weak or negligible correlations with other variables, suggesting that factors like pricing and performance ratings are not strongly dependent on age or experience. Overall, the heatmap indicates that while experience is naturally linked with age, other factors such as earnings and ratings are influenced by additional variables not captured here.

**14. Average Hourly Rate by Country**
"""

avg_country_rate = df.groupby("country")["hourly_rate (USD)"].mean().reset_index()
plt.figure(figsize=(10,5))
sns.lineplot(x="country", y="hourly_rate (USD)", data=avg_country_rate, marker="o", color="violet")
plt.xticks(rotation=45)
plt.title("Average Hourly Rate by Country")
plt.xlabel("Country")
plt.ylabel("Average Hourly Rate (USD)")
plt.show()

"""The chart shows that average hourly rates vary across countries. Some countries like Argentina, India, and the United States have higher earnings, while countries like Japan and South Korea have lower rates. Overall, most countries fall within a similar range, indicating moderate global variation in freelancer pay.

**15. Experience vs Hourly Rate and Rating**
"""

fig, axes = plt.subplots(1,2, figsize=(15,5))
sns.scatterplot(x="years_of_experience", y="hourly_rate (USD)", data=df, color="mediumvioletred", ax=axes[0])
axes[0].set_title("Experience vs Hourly Rate")
axes[0].set_xlabel("Years of Experience")
axes[0].set_ylabel("Hourly Rate (USD)")

sns.scatterplot(x="years_of_experience", y="rating", data=df, color="darkviolet", ax=axes[1])
axes[1].set_title("Experience vs Rating")
axes[1].set_xlabel("Years of Experience")
axes[1].set_ylabel("Rating")

plt.tight_layout()
plt.show()

"""**Left Plot: Experience vs Hourly Rate**

Axes:

X-axis: Years of Experience

Y-axis: Hourly Rate (USD)

**Observations from the graph:**

We see horizontal lines of dots at 20, 30, 40… USD/hour.
This happens because hourly rates are discrete, i.e., only certain values exist in the dataset.
Each line represents all freelancers earning that rate, spread across experience levels.
There are points at high hourly rates even for low experience.
Suggests that some freelancers with few years of experience still charge high rates (likely due to skill or niche demand).
Spread of points across all experience levels.
No clear upward trend, meaning experience is not the only factor influencing earnings.

**Interpretation:**

Experience affects earnings, but it’s not the only determinant — skill, reputation, and specialization matter.
Outliers at the top indicate high-earning freelancers irrespective of experience.

**Right Plot: Experience vs Rating**

Axes:

X-axis: Years of Experience

Y-axis: Rating (0–5)

**Observations from the graph:**

Ratings are mostly 1–5, with some zeros.
Points appear in horizontal clusters (e.g., many at 5, 4, 3…).
Happens because ratings are discrete values, not continuous.
No strong trend — even experienced freelancers can have low ratings.

**Interpretation:**

Experience does not guarantee a high rating.
Ratings depend more on performance, client satisfaction, and project type rather than just experience.
Most freelancers have positive ratings (3–5), but variability exists at every experience level.

**Key Insights**

**1. Experience vs Earnings**

Freelancers with higher experience levels, especially experts, tend to earn slightly higher hourly rates compared to beginners and intermediates.

**2. Skill Demand**

DevOps is the most common skill, while other skills like UI/UX, Blockchain, and Web Development also have similar representation.

**3. Skill vs Earnings**

Cybersecurity, Web Development, and DevOps have slightly higher average hourly rates compared to other skills.

**4. Gender Distribution**

The dataset shows a nearly equal number of male and female freelancers, indicating balanced participation.

**5. Gender vs Earnings**

There is no significant difference in hourly rates between male and female freelancers across all experience levels.

**6. Active Status Impact**

Active freelancers earn slightly more and have better ratings compared to inactive freelancers.

**7. Country Distribution**

South Korea has the highest number of freelancers, showing strong participation from that region.

**8. Country vs Rating**

The United States has the highest average rating, while most countries have similar rating ranges.

**9. Correlation Patterns**

Age and experience are moderately related, while other variables like hourly rate and rating show weak relationships.

**10. Client Satisfaction**

Most freelancers have high client satisfaction scores, indicating good overall performance.

**Conclusion**

The analysis of the freelancer dataset provides valuable insights into the relationship between experience, skills, earnings, and performance. It is observed that freelancers with higher experience levels, particularly experts, tend to earn slightly higher hourly rates. However, the differences are not very large, indicating that factors such as skill type and market demand also play an important role in determining earnings.

The distribution of skills shows a balanced market, with DevOps, UI/UX Design, and Blockchain Development being slightly more prominent. Technical skills such as Cybersecurity, Web Development, and DevOps offer marginally higher earning potential, suggesting that specialized skills are valued in the freelancing industry.

The dataset also highlights a balanced gender distribution with no significant difference in earnings between male and female freelancers, indicating fairness in pay. Additionally, active freelancers tend to earn more and maintain better ratings, emphasizing the importance of engagement and consistency.

Country-wise analysis shows that freelancer participation varies across regions, although performance and ratings remain relatively consistent globally. The correlation analysis reveals that age and experience are moderately related, while other variables such as hourly rate, rating, and client satisfaction are influenced by multiple external factors.

Overall, the freelancing market appears to be competitive, diverse, and performance-driven, with experience, skills, and activity level acting as the key factors influencing success.

**Future Scope / Recommendations**


- Focus on **high-demand skills** such as **DevOps, Cybersecurity,** and **AI** to increase earning potential.
- Encourage freelancers to stay **active** to improve both ratings and income.
- Perform advanced analysis such as:
  - Predicting hourly rates using machine learning models
  - Studying client satisfaction factors in detail
  - Analyzing country-wise freelancing trends
"""